// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/product/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/product/repository.go -destination=internal/domain/services/mocks/product/mock_product_repository.go -package=product
//

// Package product is a generated GoMock package.
package product

import (
	reflect "reflect"

	entities "github.com/tulioguaraldob/luizalabs-logistica-challenge/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRepository) Add(product *entities.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRepositoryMockRecorder) Add(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepository)(nil).Add), product)
}
