services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}:5432

  app:
    build: .
    container_name: go-labs-app
    env_file:
      - .env
    
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    network_mode: host
